[{ "type": "update",
   "package": "com.mobitle602",
   "apk": "/Users/bi2one/Desktop/packages/mobitle603.apk"},

 { "type": "upload",
   "apk": "/Users/bi2one/Desktop/packages/mobitle4.apk",
   "screenshots": ["/Users/bi2one/Desktop/packages/screenshots/602_1.png",
		   "/Users/bi2one/Desktop/packages/screenshots/602_2.png"],
   "icon": "/Users/bi2one/Desktop/images/icon/610.png",
   "languageElements": [{"language": "ko",
			 "title": "ko title",
			 "description": "ko description"},
			{"language": "en",
			 "title": "en title",
			 "description": "en description"},
			{"language": "fr",
			 "title": "fr title",
			 "description": "fr description"}],
   "app_type": 1,
   "category": 6,
   "contentsLevel": "low",
   "webpage": "http://mobitle.com",
   "email": "mobitle@mobitle.com" },
 
 { "type": "upload",
   "apk": "/Users/bi2one/Desktop/packages/mobitle4.apk",
   "screenshots": ["/Users/bi2one/Desktop/packages/screenshots/602_1.png",
		   "/Users/bi2one/Desktop/packages/screenshots/602_2.png"],
   "icon": "/Users/bi2one/Desktop/images/icon/610.png",
   "languageElements": [{"language": "ko",
			 "title": "ko title",
			 "description": "ko description"},
			{"language": "fr",
			 "title": "fr title",
			 "description": "fr description"}],
   "app_type": 1,
   "category": 6,
   "contentsLevel": "low",
   "webpage": "http://mobitle.com",
   "email": "mobitle@mobitle.com" }]
